### ISSUE TITLE
error: failed to get `rust-wfa2` as a dependency of package `mapquik v0.1.0 (/home/mapquik)`

### ISSUE THREAD

**Issue by husamia** [ekimb/mapquik#7]
After the command 

#cargo +nightly build --release

I get errors

   ' Updating crates.io index
    Updating git repository `https://github.com/rchikhi/rust-parallelfastx`
    Updating git repository `https://github.com/rchikhi/rust-seq2kminmers`
    Updating git repository `https://github.com/rchikhi/rust-wfa2/`
    Updating git submodule `git@github.com:smarco/WFA2-lib.git`
error: failed to get `rust-wfa2` as a dependency of package `mapquik v0.1.0 (/home/mapquik)`

Caused by:
  failed to load source for dependency `rust-wfa2`

Caused by:
  Unable to update https://github.com/rchikhi/rust-wfa2/

Caused by:
  failed to update submodule `wfa2-sys/WFA2-lib`

Caused by:
  failed to fetch submodule `wfa2-sys/WFA2-lib` from git@github.com:smarco/WFA2-lib.git

Caused by:
  failed to authenticate when downloading repository

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  error authenticating: no auth sock variable; class=Ssh (23)`

I am trying to run it in Docker container. If there is a prebuilt container that would be even better.

**Comment by ekimb** [comment]
Hello @husamia,

Can you pull the latest commit and try to compile again?

**Comment by husamia** [comment]
> Hello @husamia,
> 
> Can you pull the latest commit and try to compile again?

I compiled it again and this time it completes with no error. This is now fixed. Thank you
